# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQ4bCFLpHcpqUm_d-TrkMHUbmOu4QBCa
"""

import numpy as np
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
#Connection to Google Drive
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive/My Drive/ANNDL/Homework2

#Array che contiene le categorie di ogni time series. Dim 48000x1
categories = np.load("categories.npy")
#Array che contiene i valori delle time sesries. Dim 48000x2776
training_data = np.load("training_data.npy")
#Array che contiene gli indici che descrivono gli estremi degli intervalli validi delle time series. Dim 48000x2
valid_periods = np.load("valid_periods.npy")

categories.shape, training_data.shape, valid_periods.shape

def thePlotter(c):
    colors = sns.color_palette("dark", 6)
    fig, axes = plt.subplots(nrows=6, ncols=1, figsize=(10, 20), sharex=False)
    for i, category in enumerate(c):
      indices = np.where(categories==category)[0]
      random_indices = np.random.choice(indices, size=5, replace=False)
      start_series = np.min(valid_periods[random_indices][:,0])
      end_series = np.max(valid_periods[random_indices][:,0])
      for j in range(5):
        axes[i].plot(np.arange(start_series, training_data.shape[1]),training_data[random_indices[j], start_series:], color=colors[j], fillstyle="full")
        axes[i].set_ylabel('Value')
        axes[i].set_xlabel('Time')
        axes[i].set_title(category)
    fig.subplots_adjust(hspace=1.0)
    plt.show()

thePlotter(np.array(['A', 'B', 'C', 'D', 'E', 'F']))